name: py312_fem_class

channels:
  - conda-forge

dependencies:
  - python=3.12
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - vtk
  - pyevtk
  - h5py
  - scipy
  - pip
  - pip:
      - meshio
      - triangle